// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/RazerThemePreview.tsx": () => import("../components/mockups/RazerThemePreview.tsx"),
  "./components/mockups/razer-preview/DashboardCards.tsx": () => import("../components/mockups/razer-preview/DashboardCards.tsx"),
  "./components/mockups/razer-preview/HomeScreen.tsx": () => import("../components/mockups/razer-preview/HomeScreen.tsx")
};
